# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/davinh/guix-geng-project/myext;/home/davinh/guix-geng-project/myext-release")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "myext built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/davinh/guix-geng-project/myext-release;myext;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/davinh/Slicer-SuperBuild-Debug/SlicerExecutionModel/CMake;/home/davinh/Slicer-SuperBuild-Debug/SlicerExecutionModel/CMake;/home/davinh/Slicer-SuperBuild-Debug/SlicerExecutionModel/CMake;/home/davinh/Slicer-SuperBuild-Debug/CTKAPPLAUNCHER/CMake;/home/davinh/Slicer-SuperBuild-Debug/RapidJSON-build;/home/davinh/Slicer-SuperBuild-Debug/ITK/CMake;/home/davinh/Slicer-SuperBuild-Debug/CTKAppLauncherLib-build/CMake;/home/davinh/Slicer-SuperBuild-Debug/CTK/Utilities/CMake;/home/davinh/Slicer-SuperBuild-Debug/CTK/CMake;/home/davinh/Slicer-SuperBuild-Debug/ITK/Modules/ThirdParty/DCMTK/CMake;/home/davinh/Slicer-SuperBuild-Debug/CTK/Utilities/CMake;/home/davinh/Slicer/CMake;/home/davinh/Slicer/Extensions/CMake;/home/davinh/Slicer-SuperBuild-Debug/vtkAddon/CMake")
set(CPACK_MONOLITHIC_INSTALL "ON")
set(CPACK_NSIS_DISPLAY_NAME "myext 0.1.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MODIFY_PATH "OFF")
set(CPACK_NSIS_PACKAGE_NAME "myext 0.1.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/davinh/guix-geng-project/myext-release/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/davinh/Slicer/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "This is an example of a simple extension")
set(CPACK_PACKAGE_FILE_NAME "33241-linux-amd64-myext-localNA-")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "myext 0.1.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "myext 0.1.1")
set(CPACK_PACKAGE_NAME "myext")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "")
set(CPACK_PACKAGE_VERSION "0.1.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/davinh/Slicer/License.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.28/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;TXZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/davinh/guix-geng-project/myext-release/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "OFF")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "OFF")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/davinh/guix-geng-project/myext-release/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
